[project]
name = "roilab-r2q"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.115.11",
    "pydantic>=2.10.6",
    "redis>=5.2.1",
    "rq>=2.1.0",
    "uvicorn>=0.33.0",
]
